### ISSUE TITLE
Dependencies not installed:  nothing provides `***` needed by `****`

### ISSUE THREAD

**Issue by c2b2pss** [loosolab/TOBIAS_snakemake#5]
Snakemake errors: Many dependencies not being downloaded or installed?

```
(tobias_snakemake_env) user@pop-os:~/TOBIAS_snakemake$ snakemake --configfile example_config.yaml --use-conda --cores 6
Building DAG of jobs...
Creating conda environment environments/uropa.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /home/user/TOBIAS_snakemake/environments/uropa.yaml:
Command:
mamba env create --quiet --file "/home/user/TOBIAS_snakemake/.snakemake/conda/bd9e0dc4179dc2ab76c5ce61377855a3_.yaml" --prefix "/home/user/TOBIAS_snakemake/.snakemake/conda/bd9e0dc4179dc2ab76c5ce61377855a3_"
Output:
Encountered problems while solving:
  - nothing provides r 3.2.2* needed by r-ggplot2-2.0.0-r3.2.2_0
  - nothing provides r 3.2.2* needed by r-magrittr-1.5-r3.2.2_0
(tobias_snakemake_env) user@pop-os:~/TOBIAS_snakemake$ snakemake --configfile example_config.yaml --use-conda --cores 6
Building DAG of jobs...
Creating conda environment environments/uropa.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /home/user/TOBIAS_snakemake/environments/uropa.yaml:
Command:
mamba env create --quiet --file "/home/user/TOBIAS_snakemake/.snakemake/conda/bd9e0dc4179dc2ab76c5ce61377855a3_.yaml" --prefix "/home/user/TOBIAS_snakemake/.snakemake/conda/bd9e0dc4179dc2ab76c5ce61377855a3_"
Output:
Encountered problems while solving:
  - nothing provides r 3.2.2* needed by r-ggplot2-2.0.0-r3.2.2_0
  - nothing provides r 3.2.2* needed by r-magrittr-1.5-r3.2.2_0
  - nothing provides libcurl 7.79.0 h2574ce0_0 needed by curl-7.79.0-hea6ffbf_0
```

**Comment by msbentsen** [comment]
Hi @c2b2pss,

Can you share which OS you are using? linux/mac? I can't reproduce this on debian, so I am thinking this might be a system specific / conda issue.

**Comment by c2b2pss** [comment]
Hi,

I am using Linux (Pop OS/Ubuntu-based). I am just running this in the TOBIAS yaml generated environment.  Does this and subsequent steps pull the necessary dependencies?

BTW, I am running TOBIAS without snakemake and that works fine.  Except I don't know how to run multiple files rather than entering commands for each file (I have 7 bams+peaks). I presume snakemake would run all these one after another???

**Comment by msbentsen** [comment]
Yes, when you run snakemake with "--use-conda" it automatically builds individual conda environments for the run. However, it seems that `r=3.2.2` is not available for the system, and it can therefore not build the environment. To solve this you might try:

**Option 1:** If you are able to, you can try to install all requirements for the whole pipeline, and then run snakemake without "--use-conda". The main requirements are:
- samtools
- uropa
- bedtools
- macs2
- igvtools
- tobias

**Option 2:** R is only needed for specific options in the pipeline, so if you are just running default parameters, you can remove the requirements from the file at `environments/uropa.yaml` to look like:
```yaml
name: uropa_env

channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - python
  - numpy <1.16
  - pysam >=0.15.3
  - pip
  - pip:
    - uropa
 ```
 
 The pipeline is meant to deal with multiple .bam-files such that you do not have to run them manually (like you say). But other than that, the same TOBIAS tools are used.

**Comment by deep-buddingcoder** [comment]
Hi c2b2pss,

I am not from Looso lab but thought to contribute to the thread as I have also encountered a problem similar to the one mentioned above.

For me it had to do with the conda set up (of channel priority) 

I ran this conda command:
conda config --set channel_priority disabled

then could install TOBIAS_snakemake version.

Thanks
Deep
